[
{
 "matchedRow":1000,
      "joins":[
         {
            "value":"866077a",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"invoice_id",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"invoice_id",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	
         {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"amount_remaining",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	

         {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"base_amount_remaining",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	
        {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"usd_amount_remaining",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	
        {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"usd_invoice_amount",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         }
]
},

{
 "matchedRow":1000,
      "joins":[
         {
            "value":"767998",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"invoice_id",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"invoice_id",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	
         {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"amount_remaining",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	

         {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"base_amount_remaining",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	
        {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"usd_amount_remaining",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         },	
        {
            "value":"0.0",
            "leftTable":"xx_ap_invoices",
            "leftColumn":"usd_invoice_amount",
            "leftColumnFusionPosition":1,
            "leftColumnFusionSize":1,
            "rightColumns":[
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"base_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_amount_remaining",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               },
               {
                  "rightTable":"xx_ap_invoices",
                  "rightColumn":"usd_invoice_amount",
                  "rightColumnFusionPosition":1,
                  "rightColumnFusionSize":1
               }
            ]
         }
]
}
]
